version: '3'
services:
  web:
    image: yxh77/test:main
    ports:
      - "80:80"
    depends_on:
      - db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  db:
    build: 
      context: .
      dockerfile: step1_mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"            # 自动清理旧镜像
      WATCHTOWER_POLL_INTERVAL: 10          # 设置轮询间隔时间（秒）
      WATCHTOWER_INCLUDE_STOPPED: "true"    # 包括停止的容器
      WATCHTOWER_LABEL_ENABLE: "true"       # 只监控带有特定标签的容器
    labels:
      - "com.centurylinklabs.watchtower.enable=true"  # 仅启用监控带有此标签的容器
